### ISSUE TITLE
Skript bleibt beim Start hängen oder/und erkennt Status nicht?

### ISSUE THREAD

**Issue by Jan2220** [heikobornholdt/alarm-o-bot#3]
Hallo,
Erstmal vielen Dank für die Veröffentlichung dieses Skriptes. Nun habe ich aber ein kleines Problem, denn beim Starten des Skriptes kommt, obwohl keine Alarmierung am Melder vorhanden ist, diese Nachricht:

`Beginne mit Überwachung des Status. Aktuell: Unquittiere Alarmierungen vorhanden!`

Außerdem passiert nach dieser Nachricht nichts mehr und die Skripte in den started/enabled & ended/enabled Ordnern werden ebenfalls nicht ausgeführt. Liegt es vielleicht daran dass die Nachricht oben einfach falsch geschrieben ist? Dass es eigentlich heißen sollte, dass keine Unquittierten Alarmierungen vorhanden sind?
Ich hoffe Sie können mir evtl. helfen und ggf. das Skript überarbeiten sollte es nicht an mir liegen.
"Verkabelt" habe ich auch soweit alles richtig nach dem Schaltplan.
Den GPIO Port 21 habe ich auch in /sys/class/gpio/export geschrieben und auch denselben befehl zum Ausführen benutzt wie in der README.md hinterlegt.

MfG,
Jan

**Comment by Jan2220** [comment]
Ok, hab da glaub ich was falsch verstanden einfach ignorieren :D

**Comment by HeikoBornholdt** [comment]
Moin,

Entschuldigung. Ich habe dein Issue erst jetzt gesehen 😞.

Falls du das Problem noch hast: Magst du bitte einmal `cat /sys/class/gpio/gpio21/value` in der Shell ausführen und das Ergebnis zeigen?

Danke!

**Comment by Jan2220** [comment]
Oups, macht nichts. Hatte es schon gelöst bekommen und diesen Eintrag hier selbst vergessen bzw. nicht geschlossen. Hat sich also erledigt.
Trotzdem vielen Dank 👍

**Comment by HeikoBornholdt** [comment]
Alles klar. Freut mich zu hören! 🖖 

---
Gruß, Heiko
